//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportingInMVC.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemp
    {
        public int emp_id { get; set; }
        public string emp_name { get; set; }
        public string emp_add { get; set; }
        public string emp_mob { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
    }
}
